[tool.poetry]
name = "healthcheck"
version = "1.3.0"
description = "Internal service endpoint health check for Spatial Support System"
authors = ["ASI <asi@dbca.wa.gov.au>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
bottle = "0.12.25"
requests = "2.32.3"
pytz = "2024.1"
python-dotenv = "1.0.1"
gunicorn = "22.0.0"
humanize = "4.9.0"

[tool.poetry.group.dev.dependencies]
ipython = "^8.26.0"
pre-commit = "^3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
