[tool.poetry]
name = "healthcheck"
version = "1.3.2"
description = "Internal service endpoint health check for Spatial Support System"
authors = ["ASI <asi@dbca.wa.gov.au>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
bottle = "0.13.1"
requests = "2.32.3"
pytz = "2024.1"
python-dotenv = "1.0.1"
gunicorn = "23.0.0"
humanize = "4.10.0"
defusedxml = "0.7.1"

[tool.poetry.group.dev.dependencies]
ipython = "^8.27.0"
pre-commit = "^3.7.1"

# Reference: https://docs.astral.sh/ruff/configuration/
[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
  "E501", # Line too long
  "E722", # Bare except
]

# Reference: https://www.djlint.com/docs/configuration/
[tool.djlint]
profile = "django"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
