[tool.poetry]
name = "healthcheck"
version = "1.1.9"
description = "Internal service endpoint health check for Spatial Support System"
authors = ["ASI <asi@dbca.wa.gov.au>"]

[tool.poetry.dependencies]
python = "^3.9"
bottle = "0.12.24"
requests = "2.28.2"
python-dateutil = "2.8.2"
pytz = "2022.7.1"
python-dotenv = "0.21.1"

[tool.poetry.group.dev.dependencies]
ipython = "^8.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
