[tool.poetry]
name = "healthcheck"
version = "1.1.17"
description = "Internal service endpoint health check for Spatial Support System"
authors = ["ASI <asi@dbca.wa.gov.au>"]

[tool.poetry.dependencies]
python = "^3.10"
bottle = "0.12.25"
requests = "2.31.0"
pytz = "2024.1"
python-dotenv = "1.0.1"
gunicorn = "21.2.0"

[tool.poetry.group.dev.dependencies]
ipython = "^8.21.0"
pre-commit = "^3.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
