apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-deployment
spec:
  template:
    spec:
      containers:
        - name: healthcheck
          envFrom:
            - secretRef:
                name: healthcheck-env-uat
                optional: false
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
        - key: arch
          operator: Equal
          value: arm64
          effect: NoSchedule
